;;;;
;;;; File generated by cpct_aks2c CPCtelera script
;;;; Souce file of this conversion: assets/music/banger.aks
;;;; Generation time: Thu Oct 28 22:34:13 CEST 2021
;;;;

;;;; Song 'cancion1' metadata constants
cancion1_address = 0x02E5
cancion1_size    = 135
cancion1_end     = 0x36b

;;;; Song 'cancion1' declaration
.globl _cancion1
