;;;;
;;;; File generated by cpct_aks2c CPCtelera script
;;;; Souce file of this conversion: assets/music/banger2.aks
;;;; Generation time: jue 28 oct 2021 01:05:38 CEST
;;;;

;;;; Song 'cancion1' metadata constants
cancion1_address = 0x40
cancion1_size    = 165
cancion1_end     = 0xe4

;;;; Song 'cancion1' declaration
.globl _cancion1
