;;;;
;;;; File generated by cpct_aks2c CPCtelera script
;;;; Souce file of this conversion: assets/music/bangerazo.aks
;;;; Generation time: Tue Nov  2 12:53:59 CET 2021
;;;;

;;;; Song 'cancion1' metadata constants
cancion1_address = 0x02E5
cancion1_size    = 215
cancion1_end     = 0x3bb

;;;; Song 'cancion1' declaration
.globl _cancion1
