;;;;
;;;; File generated by cpct_aks2c CPCtelera script
;;;; Souce file of this conversion: assets/music/banger.aks
;;;; Generation time: Thu Oct 28 21:32:07 CEST 2021
;;;;

;;;; Song 'cancion1' metadata constants
cancion1_address = 0x0136
cancion1_size    = 135
cancion1_end     = 0x1bc

;;;; Song 'cancion1' declaration
.globl _cancion1
