;;;;
;;;; File generated by cpct_aks2c CPCtelera script
;;;; Souce file of this conversion: assets/music/banger2.aks
;;;; Generation time: Thu Oct 28 21:32:08 CEST 2021
;;;;

;;;; Song 'cancion2' metadata constants
cancion2_address = 0x0091
cancion2_size    = 165
cancion2_end     = 0x135

;;;; Song 'cancion2' declaration
.globl _cancion2
