;;;;
;;;; File generated by cpct_aks2c CPCtelera script
;;;; Souce file of this conversion: assets/music/explosion.aks
;;;; Generation time: sáb 30 oct 2021 22:30:25 CEST
;;;;

;;;; Song 'pew2' metadata constants
pew2_address = 0x03ae
pew2_size    = 67
pew2_end     = 0x3f0

;;;; Song 'pew2' declaration
.globl _pew2
