;;;;
;;;; File generated by cpct_aks2c CPCtelera script
;;;; Souce file of this conversion: assets/music/pew.aks
;;;; Generation time: Tue Nov  2 12:53:58 CET 2021
;;;;

;;;; Song 'pew' metadata constants
pew_address = 0x03bc
pew_size    = 67
pew_end     = 0x3fe

;;;; Song 'pew' declaration
.globl _pew
