;;;;
;;;; File generated by cpct_aks2c CPCtelera script
;;;; Souce file of this conversion: assets/music/pew.aks
;;;; Generation time: sáb 30 oct 2021 22:30:25 CEST
;;;;

;;;; Song 'pew' metadata constants
pew_address = 0x036c
pew_size    = 67
pew_end     = 0x3ae

;;;; Song 'pew' declaration
.globl _pew
