;;;;
;;;; File generated by cpct_aks2c CPCtelera script
;;;; Souce file of this conversion: assets/music/pew.aks
;;;; Generation time: dom 05 dic 2021 11:51:41 CET
;;;;

;;;; Song 'pew' metadata constants
pew_address = 0x03bc
pew_size    = 67
pew_end     = 0x3fe

;;;; Song 'pew' declaration
.globl _pew
